#!/bin/bash
set -euo pipefail
PATH=$PATH:/usr/lib/x86_64-linux-gnu/glib-2.0/
ARCH=x86_64 ./pkg2appimage recipes/client.yml 2>&1 | tee build.log
ls -1 /root/out/Plastic_SCM*.AppImage | cut -f 2,3 -d. > SUFFIX
ls -1 Plastic_SCM/plasticscm-client-core*.deb | cut -f3 -d_ > VERSION
mv /root/out/Plastic_SCM*.AppImage /root/out/Plastic_SCM_Client.AppImage
mkdir icons apps
cp /root/Plastic_SCM/Plastic_SCM.AppDir/opt/plasticscm5/theme/avalonia/icons/lingluonx.ico icons/
cp /root/Plastic_SCM/Plastic_SCM.AppDir/opt/plasticscm5/theme/avalonia/icons/linplasticx.ico icons/
cp /root/Plastic_SCM/Plastic_SCM.AppDir/usr/share/applications/plasticx.desktop apps/
cp /root/Plastic_SCM/Plastic_SCM.AppDir/usr/share/applications/gluonx.desktop apps/
